/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/about/about.vue')['default']
    AboutCard: typeof import('./src/components/about/aboutCard.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Blog: typeof import('./src/components/blog/blog.vue')['default']
    Contact: typeof import('./src/components/contact/contact.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Hero: typeof import('./src/components/sections/hero.vue')['default']
    Products: typeof import('./src/components/products/products.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Schedule: typeof import('./src/components/schedule/schedule.vue')['default']
    Services: typeof import('./src/components/offers/services.vue')['default']
    Testimonials: typeof import('./src/components/testimonials/testimonials.vue')['default']
    Treatments: typeof import('./src/components/treatments/treatments.vue')['default']
  }
}
