/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/about/about.vue')['default']
    AboutCard: typeof import('./src/components/about/aboutCard.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Schedule: typeof import('./src/components/schedule/schedule.vue')['default']
  }
}
